[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "word-game-kivy"
version = "0.2.0"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["word_game_kivy*"]
