name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      KIVY_WINDOW: mock
      KIVY_GL_BACKEND: mock
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install ruff black mypy pytest

      - name: Ruff (check)
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: Mypy
        run: mypy --config-file mypy.ini .

      - name: Pytest (headless)
        run: xvfb-run -a pytest -q
